server:
  port: 8081
  #servlet:
    #context-path: /supplier-ms

spring:
  application:
    name: 'supplier'

  datasource:
    url: jdbc:h2:mem:supplier
    driver-class-name: org.h2.Driver
    username: sa
    password: 
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    