server:
  port: 8081
  servlet:
    context-path: /supplier-ms

spring:
  application:
    name: 'supplier'

  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:h2:mem:baseapp
    driver-class-name: org.h2.Driver
    username: sa
    password: 
    
    