server:
  port: 8081
  servlet:
    context-path: /supplier-ms

spring:
  application:
    name: 'supplier'

  datasource:
    url: jdbc:h2:mem:supplier
    driver-class-name: org.h2.Driver
    username: sa
    password: 
    
    