server:
  port: 8888
  
spring:
  cloud:
    config:
      server:
        git:
          #you must define the name of branch on git repository
          default-label: main
          uri: https://github.com/davidkmaia/spring-cloud-microservices-sample-repo
          search-paths: supplier