server:
  port: 8888
  
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: /home/david/Dev/Projetos/Estudos/spring-cloud-microservices-sample/microservices-repo